linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - misspell
    - goconst
    - golint
    - errcheck
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode

issues:
  exclude-use-default: false

linters-settings:
  goconst:
    min-occurrences: 6
