linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - goconst
    - golint
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - scopelint

issues:
  exclude-use-default: false

linters-settings:
  goconst:
    min-occurrences: 6
